CREATE DATABASE IF NOT EXISTS TodoApp;
USE TodoApp;

CREATE TABLE IF NOT EXISTS UrgencyLookup (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(20) NOT NULL,
	ColorRGB CHAR(7) NOT NULL,
	
	CONSTRAINT CheckUrgencyColor
	CHECK (ColorRGB REGEXP "^#[0-9A-Fa-f]{6}$")
);


CREATE TABLE IF NOT EXISTS StatusLookup (
	Id INT NOT NULL PRIMARY KEY, -- set manually, is indicative of progress
	Name VARCHAR(20) NOT NULL,
	ColorRGB CHAR(7) NOT NULL,
	
	CONSTRAINT CheckStatusColor
	CHECK (ColorRGB REGEXP "^#[0-9A-Fa-f]{6}$")
);

CREATE TABLE IF NOT EXISTS Task (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ParentTaskId INT REFERENCES Task(Id) ON DELETE CASCADE,
	DueDate DATE,
	DueTime TIME,
	UrgencyId INT REFERENCES UrgencyLookup(Id) ON DELETE SET NULL,
	StatusId INT REFERENCES StatusLookup(Id) ON DELETE SET NULL,
	Description TEXT
);

CREATE TABLE IF NOT EXISTS Tag (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS TaskTagXref (
	TaskId INT NOT NULL REFERENCES Task(Id) ON DELETE CASCADE,
	TagId INT NOT NULL REFERENCES Tag(Id) ON DELETE CASCADE,
	PRIMARY KEY (TaskId, TagId)
);
